version: '3'
services:
  solr:
    image: solr:8
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
      - $PWD/solr/:/opt/solr/configs
    command:
      - solr-precreate
      - blacklight-core-dev 
      - /opt/solr/configs/ 
volumes:
  data:
